from pathlib import Path
p=Path('worker.js'); s=p.read_text()
assert "const VERSION = 'RADAR v0.4.7.47 Cloud';" in s
assert 'id="dateClock"' in s and 'id="trackRadarTab"' in s and 'id="trackRadarShell"' in s
s=s.replace('id="trackRadarTab" type="button">TRACK RADAR</button>','id="trackRadarTab" type="button">ARTIST RADAR</button>',1)
start=s.index('<div id="trackRadarShell"')
end=s.index('\n<div class="grid">',start)
new_shell='''<div id="trackRadarShell" style="display:none;margin-bottom:14px"><div class="field"><label>Artista da analizzare</label><input id="artistRadarInput" placeholder="es. ORBYT oppure link profilo Spotify" autocomplete="off" /></div><div class="actions" style="margin-top:10px"><button class="btn" id="artistRadarScan" type="button">Scansiona artista</button><span class="status" id="artistRadarStatus">Cerca dove compaiono le tracce dell’artista.</span></div><div id="artistRadarSummary" style="display:none;margin-top:12px;padding:10px;border:1px solid var(--line);border-radius:13px;background:#0a0d1b"></div><div class="status" style="margin-top:9px">RADAR cerca più tracce dello stesso artista, raggruppa i placement per playlist ed esclude le sorgenti Spotify algoritmiche. I risultati dipendono da ciò che è pubblicamente indicizzato sul web.</div><div id="artistRadarResults" style="margin-top:14px"></div><div class="actions" style="display:none"></div></div>'''
s=s[:start]+new_shell+s[end:]
front="document.addEventListener('click',function(e){if(e.target&&e.target.id==='trackRadarScan')scanTrackRadarPlacements()});"
assert front in s
js="""
async function scanArtistRadar(){const input=document.getElementById('artistRadarInput'),btn=document.getElementById('artistRadarScan'),st=document.getElementById('artistRadarStatus'),sum=document.getElementById('artistRadarSummary'),box=document.getElementById('artistRadarResults');if(!input||!btn||!st||!sum||!box)return;const artist=input.value.trim();if(!artist){st.textContent='Inserisci il nome artista o il link Spotify.';return}btn.disabled=true;st.textContent='Analizzo catalogo e placement pubblici…';sum.style.display='none';box.innerHTML='';try{const r=await fetch('/api/artist-radar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({artist:artist})});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Errore Artist Radar');const tracks=Array.isArray(d.tracks)?d.tracks:[],rows=Array.isArray(d.playlists)?d.playlists:[];sum.style.display='block';sum.textContent=(d.artist||artist)+' · '+tracks.length+' tracce analizzate · '+rows.length+' playlist rilevate';st.textContent=rows.length?'Trovate '+rows.length+' playlist pubblicamente rilevabili.':'Nessuna playlist pubblicamente rilevabile.';for(const x of rows){const card=document.createElement('div');card.className='result';const h=document.createElement('h3');h.textContent=x.name||'Spotify playlist';const meta=document.createElement('div');meta.className='muted';meta.textContent=(x.owner?x.owner+' · ':'')+(x.trackCount||0)+' tracce dell’artista rilevate';const names=document.createElement('div');names.className='muted';names.style.marginTop='6px';names.textContent=(x.tracks||[]).slice(0,8).join(' · ');card.append(h,meta,names);if(x.spotifyUrl){const a=document.createElement('a');a.href=x.spotifyUrl;a.target='_blank';a.rel='noopener';a.className='btn secondary';a.style.cssText='display:inline-block;margin-top:10px;text-decoration:none';a.textContent='Apri Spotify';card.appendChild(a)}box.appendChild(card)}}catch(e){st.textContent=e.message||'Errore Artist Radar'}finally{btn.disabled=false}}
document.addEventListener('click',function(e){if(e.target&&e.target.id==='artistRadarScan')scanArtistRadar()});
"""
s=s.replace(front,front+js,1)
backend='function trackRadarAlgorithmic(name)'
assert backend in s
helpers="""
function artistRadarInputName(raw){const x=String(raw||'').trim();try{const u=new URL(x);const parts=u.pathname.split('/').filter(Boolean);if(u.hostname==='open.spotify.com'&&parts[0]==='artist'&&parts[1])return {artistId:parts[1],name:''}}catch(e){}return {artistId:'',name:x}}
async function artistRadarCatalog(raw,env){const q=artistRadarInputName(raw),token=await spotifyAccessToken(env);if(!token)throw new Error('Spotify non disponibile');let artistName=q.name,artistId=q.artistId;if(artistId&&!artistName){const ar=await fetch('https://api.spotify.com/v1/artists/'+encodeURIComponent(artistId),{headers:{Authorization:'Bearer '+token}});if(ar.ok){const ad=await ar.json();artistName=String(ad.name||'').trim()}}if(!artistName)throw new Error('Artista non riconosciuto');const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q','artist:'+artistName);u.searchParams.set('type','track');u.searchParams.set('limit','50');const r=await fetch(u,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw new Error('Catalogo Spotify non disponibile');const d=await r.json(),seen=new Set(),tracks=[];for(const t of d.tracks?.items||[]){const arts=(t.artists||[]).map(a=>String(a.name||'').trim());if(!arts.some(a=>normalize(a)===normalize(artistName)))continue;const name=String(t.name||'').trim(),k=normalize(name);if(!name||seen.has(k))continue;seen.add(k);tracks.push({name,spotifyUrl:String(t.external_urls?.spotify||'')});if(tracks.length>=16)break}return {artist:artistName,tracks}}
async function artistRadarScan(input,env){const cat=await artistRadarCatalog(input?.artist,env),playlistMap=new Map();const jobs=[];for(const t of cat.tracks){const qs=['"'+t.name+'" "'+cat.artist+'" "Spotify playlist"','"'+t.name+'" "'+cat.artist+'" open.spotify.com/playlist'];for(const q of qs)jobs.push({track:t.name,p:smartSearch(q,env,18)})}const done=await Promise.all(jobs.map(async j=>({track:j.track,batch:await j.p})));for(const j of done){for(const r of j.batch.results||[]){let clean=cleanPlaylistUrl(r.url||'');if(!clean){const m=String((r.title||'')+' '+(r.description||'')).match(/https?:\\/\\/open\\.spotify\\.com\\/playlist\\/[A-Za-z0-9]+/i);if(m)clean=cleanPlaylistUrl(m[0])}if(!clean)continue;const text=normalize((r.title||'')+' '+(r.description||''));if(!text.includes(normalize(j.track))||!text.includes(normalize(cat.artist)))continue;const id=new URL(clean).pathname.split('/').filter(Boolean)[1];if(!id)continue;let x=playlistMap.get(id);if(!x){x={playlistId:id,spotifyUrl:clean,name:String(r.title||'Spotify playlist').trim(),owner:'',tracks:new Set(),evidence:[]};playlistMap.set(id,x)}x.tracks.add(j.track);if(x.evidence.length<3)x.evidence.push(String((r.title||'')+' — '+(r.description||'')).slice(0,240))}}}const out=[];for(const x of [...playlistMap.values()].slice(0,30)){try{const ident=await spotifyPlaylistIdentity(x.spotifyUrl,env);if(ident){x.name=ident.name||x.name;x.owner=ident.owner||''}}catch(e){}if(trackRadarAlgorithmic(x.name))continue;const tracks=[...x.tracks];out.push({playlistId:x.playlistId,spotifyUrl:x.spotifyUrl,name:x.name,owner:x.owner,tracks,trackCount:tracks.length,evidence:x.evidence})}out.sort((a,b)=>b.trackCount-a.trackCount||String(a.name).localeCompare(String(b.name)));return {artist:cat.artist,tracks:cat.tracks,playlists:out}}
"""
s=s.replace(backend,helpers+backend,1)
route="if(url.pathname==='/api/track-radar'&&request.method==='POST')"
assert route in s
s=s.replace(route,"if(url.pathname==='/api/artist-radar'&&request.method==='POST'){try{return json(await artistRadarScan(await request.json(),env))}catch(e){return json({error:e.message||'Errore Artist Radar'},500)}}"+route,1)
s=s.replace("const VERSION = 'RADAR v0.4.7.47 Cloud';","const VERSION = 'RADAR v0.4.7.48 Cloud';",1)
s=s.replace('<div class="version">v0.4.7.47</div>','<div class="version">v0.4.7.48</div>',1)
p.write_text(s)
# trigger 2
