from pathlib import Path
p=Path('worker.js'); s=p.read_text()
assert "const VERSION = 'RADAR v0.4.7.48 Cloud';" in s
old="""async function artistRadarCatalog(raw,env){const q=artistRadarInputName(raw),token=await spotifyAccessToken(env);if(!token)throw new Error('Spotify non disponibile');let artistName=q.name,artistId=q.artistId;if(artistId&&!artistName){const ar=await fetch('https://api.spotify.com/v1/artists/'+encodeURIComponent(artistId),{headers:{Authorization:'Bearer '+token}});if(ar.ok){const ad=await ar.json();artistName=String(ad.name||'').trim()}}if(!artistName)throw new Error('Artista non riconosciuto');const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q','artist:'+artistName);u.searchParams.set('type','track');u.searchParams.set('limit','50');const r=await fetch(u,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw new Error('Catalogo Spotify non disponibile');const d=await r.json(),seen=new Set(),tracks=[];for(const t of d.tracks?.items||[]){const arts=(t.artists||[]).map(a=>String(a.name||'').trim());if(!arts.some(a=>normalize(a)===normalize(artistName)))continue;const name=String(t.name||'').trim(),k=normalize(name);if(!name||seen.has(k))continue;seen.add(k);tracks.push({name,spotifyUrl:String(t.external_urls?.spotify||'')});if(tracks.length>=16)break}return {artist:artistName,tracks}}"""
assert old in s
new="""async function artistRadarCatalog(raw,env){const q=artistRadarInputName(raw),token=await spotifyAccessToken(env);if(!token)throw new Error('Spotify non disponibile');let artistName=q.name,artistId=q.artistId;if(artistId&&!artistName){const ar=await fetch('https://api.spotify.com/v1/artists/'+encodeURIComponent(artistId),{headers:{Authorization:'Bearer '+token}});if(ar.ok){const ad=await ar.json();artistName=String(ad.name||'').trim()}}if(!artistName)throw new Error('Artista non riconosciuto');const seen=new Set(),tracks=[];for(const offset of [0,10,20,30]){const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q','artist:'+artistName);u.searchParams.set('type','track');u.searchParams.set('limit','10');u.searchParams.set('offset',String(offset));const r=await fetch(u,{headers:{Authorization:'Bearer '+token}});if(!r.ok){let detail='';try{detail=await r.text()}catch(e){}throw new Error('Catalogo Spotify non disponibile'+(r.status?' · '+r.status:'')+(detail?' · '+detail.slice(0,120):''))}const d=await r.json();const items=d.tracks?.items||[];for(const t of items){const arts=(t.artists||[]).map(a=>String(a.name||'').trim());if(!arts.some(a=>normalize(a)===normalize(artistName)))continue;const name=String(t.name||'').trim(),k=normalize(name);if(!name||seen.has(k))continue;seen.add(k);tracks.push({name,spotifyUrl:String(t.external_urls?.spotify||'')});if(tracks.length>=16)break}if(tracks.length>=16||items.length<10)break}if(!tracks.length)throw new Error('Nessuna traccia Spotify trovata per '+artistName);return {artist:artistName,tracks}}"""
s=s.replace(old,new,1)
s=s.replace("const VERSION = 'RADAR v0.4.7.48 Cloud';","const VERSION = 'RADAR v0.4.7.49 Cloud';",1)
s=s.replace('<div class="version">v0.4.7.48</div>','<div class="version">v0.4.7.49</div>',1)
p.write_text(s)
# trigger
