from pathlib import Path
p=Path('worker.js'); s=p.read_text()
assert "const VERSION = 'RADAR v0.4.7.50 Cloud';" in s
start=s.index('async function artistRadarScan(input,env)')
end=s.index('\nfunction trackRadarAlgorithmic(name)',start)
new_scan="""async function artistRadarScan(input,env){const cat=await artistRadarCatalog(input?.artist,env),playlistMap=new Map(),foundTracks=new Set();const ingest=(track,batch,stage)=>{for(const r of batch.results||[]){let clean=cleanPlaylistUrl(r.url||'');if(!clean){const m=String((r.title||'')+' '+(r.description||'')).match(/https?:\\/\\/open\\.spotify\\.com\\/playlist\\/[A-Za-z0-9]+/i);if(m)clean=cleanPlaylistUrl(m[0])}if(!clean)continue;const blob=String((r.title||'')+' '+(r.description||'')),text=normalize(blob);if(!text.includes(normalize(track))||!text.includes(normalize(cat.artist)))continue;const id=new URL(clean).pathname.split('/').filter(Boolean)[1];if(!id)continue;foundTracks.add(normalize(track));let x=playlistMap.get(id);if(!x){x={playlistId:id,spotifyUrl:clean,name:String(r.title||'Spotify playlist').trim(),owner:'',tracks:new Set(),evidence:[],stages:new Set()};playlistMap.set(id,x)}x.tracks.add(track);x.stages.add(stage);if(x.evidence.length<3)x.evidence.push(blob.slice(0,240))}};const fastJobs=cat.tracks.map(t=>({track:t.name,p:smartSearch('\\"'+t.name+'\\" \\"'+cat.artist+'\\" Spotify playlist',env,12)}));const fast=await Promise.all(fastJobs.map(async j=>({track:j.track,batch:await j.p})));for(const j of fast)ingest(j.track,j.batch,'fast');const missing=cat.tracks.filter(t=>!foundTracks.has(normalize(t.name))).slice(0,5);if(missing.length&&playlistMap.size<8){const deepJobs=[];for(const t of missing){deepJobs.push({track:t.name,p:smartSearch('site:open.spotify.com/playlist \\"'+t.name+'\\" \\"'+cat.artist+'\\"',env,16)});deepJobs.push({track:t.name,p:smartSearch('\\"'+t.name+'\\" \\"'+cat.artist+'\\" playlist Spotify -album -track',env,16)})}const deep=await Promise.all(deepJobs.map(async j=>({track:j.track,batch:await j.p})));for(const j of deep)ingest(j.track,j.batch,'deep')}const candidates=[...playlistMap.values()].slice(0,16);const enriched=await Promise.all(candidates.map(async x=>{try{const ident=await spotifyPlaylistIdentity(x.spotifyUrl,env);if(ident){x.name=ident.name||x.name;x.owner=ident.owner||''}}catch(e){}return x}));const out=[];const an=normalize(cat.artist).replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim();for(const x of enriched){const pn=normalize(x.name).replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim();if(trackRadarAlgorithmic(x.name)||pn.startsWith(an+' radio'))continue;const tracks=[...x.tracks],stages=[...x.stages];out.push({playlistId:x.playlistId,spotifyUrl:x.spotifyUrl,name:x.name,owner:x.owner,tracks,trackCount:tracks.length,evidence:x.evidence,stage:stages.includes('deep')?'deep':'fast'})}out.sort((a,b)=>b.trackCount-a.trackCount||(a.stage===b.stage?0:a.stage==='deep'?-1:1)||String(a.name).localeCompare(String(b.name)));return {artist:cat.artist,tracks:cat.tracks,playlists:out,mode:'two-stage',deepTracks:missing.map(x=>x.name)}}"""
s=s[:start]+new_scan+s[end:]
s=s.replace("const VERSION = 'RADAR v0.4.7.50 Cloud';","const VERSION = 'RADAR v0.4.7.51 Cloud';",1)
s=s.replace('<div class="version">v0.4.7.50</div>','<div class="version">v0.4.7.51</div>',1)
p.write_text(s)
# trigger-1
