from pathlib import Path
p=Path('worker.js'); s=p.read_text()
assert "const VERSION = 'RADAR v0.4.7.49 Cloud';" in s
old_catalog="""async function artistRadarCatalog(raw,env){const q=artistRadarInputName(raw),token=await spotifyAccessToken(env);if(!token)throw new Error('Spotify non disponibile');let artistName=q.name,artistId=q.artistId;if(artistId&&!artistName){const ar=await fetch('https://api.spotify.com/v1/artists/'+encodeURIComponent(artistId),{headers:{Authorization:'Bearer '+token}});if(ar.ok){const ad=await ar.json();artistName=String(ad.name||'').trim()}}if(!artistName)throw new Error('Artista non riconosciuto');const seen=new Set(),tracks=[];for(const offset of [0,10,20,30]){const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q','artist:'+artistName);u.searchParams.set('type','track');u.searchParams.set('limit','10');u.searchParams.set('offset',String(offset));const r=await fetch(u,{headers:{Authorization:'Bearer '+token}});if(!r.ok){let detail='';try{detail=await r.text()}catch(e){}throw new Error('Catalogo Spotify non disponibile'+(r.status?' · '+r.status:'')+(detail?' · '+detail.slice(0,120):''))}const d=await r.json();const items=d.tracks?.items||[];for(const t of items){const arts=(t.artists||[]).map(a=>String(a.name||'').trim());if(!arts.some(a=>normalize(a)===normalize(artistName)))continue;const name=String(t.name||'').trim(),k=normalize(name);if(!name||seen.has(k))continue;seen.add(k);tracks.push({name,spotifyUrl:String(t.external_urls?.spotify||'')});if(tracks.length>=16)break}if(tracks.length>=16||items.length<10)break}if(!tracks.length)throw new Error('Nessuna traccia Spotify trovata per '+artistName);return {artist:artistName,tracks}}"""
new_catalog="""async function artistRadarCatalog(raw,env){const q=artistRadarInputName(raw),token=await spotifyAccessToken(env);if(!token)throw new Error('Spotify non disponibile');let artistName=q.name,artistId=q.artistId;if(artistId&&!artistName){const ar=await fetch('https://api.spotify.com/v1/artists/'+encodeURIComponent(artistId),{headers:{Authorization:'Bearer '+token}});if(ar.ok){const ad=await ar.json();artistName=String(ad.name||'').trim()}}if(!artistName)throw new Error('Artista non riconosciuto');const seen=new Set(),tracks=[];for(const offset of [0,10]){const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q','artist:'+artistName);u.searchParams.set('type','track');u.searchParams.set('limit','10');u.searchParams.set('offset',String(offset));const r=await fetch(u,{headers:{Authorization:'Bearer '+token}});if(!r.ok){let detail='';try{detail=await r.text()}catch(e){}throw new Error('Catalogo Spotify non disponibile'+(r.status?' · '+r.status:'')+(detail?' · '+detail.slice(0,120):''))}const d=await r.json();const items=d.tracks?.items||[];for(const t of items){const arts=(t.artists||[]).map(a=>String(a.name||'').trim());if(!arts.some(a=>normalize(a)===normalize(artistName)))continue;const name=String(t.name||'').trim(),k=normalize(name);if(!name||seen.has(k))continue;seen.add(k);tracks.push({name,spotifyUrl:String(t.external_urls?.spotify||'')});if(tracks.length>=8)break}if(tracks.length>=8||items.length<10)break}if(!tracks.length)throw new Error('Nessuna traccia Spotify trovata per '+artistName);return {artist:artistName,tracks}}"""
assert old_catalog in s
s=s.replace(old_catalog,new_catalog,1)
start=s.index('async function artistRadarScan(input,env)')
end=s.index('\nfunction trackRadarAlgorithmic(name)',start)
new_scan="""async function artistRadarScan(input,env){const cat=await artistRadarCatalog(input?.artist,env),playlistMap=new Map();const jobs=cat.tracks.map(t=>({track:t.name,p:smartSearch('\\"'+t.name+'\\" \\"'+cat.artist+'\\" Spotify playlist',env,12)}));const done=await Promise.all(jobs.map(async j=>({track:j.track,batch:await j.p})));for(const j of done){for(const r of j.batch.results||[]){let clean=cleanPlaylistUrl(r.url||'');if(!clean){const m=String((r.title||'')+' '+(r.description||'')).match(/https?:\\/\\/open\\.spotify\\.com\\/playlist\\/[A-Za-z0-9]+/i);if(m)clean=cleanPlaylistUrl(m[0])}if(!clean)continue;const text=normalize((r.title||'')+' '+(r.description||''));if(!text.includes(normalize(j.track))||!text.includes(normalize(cat.artist)))continue;const id=new URL(clean).pathname.split('/').filter(Boolean)[1];if(!id)continue;let x=playlistMap.get(id);if(!x){x={playlistId:id,spotifyUrl:clean,name:String(r.title||'Spotify playlist').trim(),owner:'',tracks:new Set(),evidence:[]};playlistMap.set(id,x)}x.tracks.add(j.track);if(x.evidence.length<2)x.evidence.push(String((r.title||'')+' — '+(r.description||'')).slice(0,220))}}const candidates=[...playlistMap.values()].slice(0,12);const enriched=await Promise.all(candidates.map(async x=>{try{const ident=await spotifyPlaylistIdentity(x.spotifyUrl,env);if(ident){x.name=ident.name||x.name;x.owner=ident.owner||''}}catch(e){}return x}));const out=[];const an=normalize(cat.artist).replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim();for(const x of enriched){const pn=normalize(x.name).replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim();if(trackRadarAlgorithmic(x.name)||pn.startsWith(an+' radio'))continue;const tracks=[...x.tracks];out.push({playlistId:x.playlistId,spotifyUrl:x.spotifyUrl,name:x.name,owner:x.owner,tracks,trackCount:tracks.length,evidence:x.evidence})}out.sort((a,b)=>b.trackCount-a.trackCount||String(a.name).localeCompare(String(b.name)));return {artist:cat.artist,tracks:cat.tracks,playlists:out,mode:'fast'}}"""
s=s[:start]+new_scan+s[end:]
s=s.replace("const VERSION = 'RADAR v0.4.7.49 Cloud';","const VERSION = 'RADAR v0.4.7.50 Cloud';",1)
s=s.replace('<div class="version">v0.4.7.49</div>','<div class="version">v0.4.7.50</div>',1)
p.write_text(s)
# trigger
