from pathlib import Path
p=Path('worker.js'); s=p.read_text()
assert "const VERSION = 'RADAR v0.4.7.46 Cloud';" in s
assert 'id="dateClock"' in s and 'id="trackRadarTab"' in s and 'id="trackRadarScan"' in s
marker='<div id="trackRadarResults" style="margin-top:14px"></div>'
assert marker in s and 'id="s4aPlacements"' not in s
ui='<div id="s4aImportBox" style="margin-top:14px;padding:13px;border:1px solid #2c3964;border-radius:14px;background:#090d1a"><div style="font-size:11px;font-weight:900;letter-spacing:.1em;color:var(--green)">SPOTIFY FOR ARTISTS · ASSISTED IMPORT</div><div class="status" style="margin:6px 0 9px">Incolla i nomi delle playlist mostrate in Spotify for Artists, una per riga. Le sorgenti algoritmiche vengono escluse.</div><textarea id="s4aPlacements" placeholder="SEX EDM - Sensual &amp; Sexy Deep House&#10;Great Vibes: Chill Dance &amp; Feel-Good House&#10;Voodoo 11/09" style="width:100%;min-height:104px;border:1px solid #30385f;background:#0a0d1b;color:#fff;border-radius:12px;padding:11px;resize:vertical;font:inherit"></textarea><div class="actions" style="margin-top:9px"><button class="btn secondary" id="s4aMatch" type="button">Importa e identifica</button><span class="status" id="s4aStatus">0 placement importati</span></div><div id="s4aResults" style="margin-top:10px"></div></div>'
s=s.replace(marker,ui+marker,1)
front="document.addEventListener('click',function(e){if(e.target&&e.target.id==='trackRadarScan')scanTrackRadarPlacements()});"
assert front in s
js="""
async function importS4APlacements(){const ta=document.getElementById('s4aPlacements'),btn=document.getElementById('s4aMatch'),st=document.getElementById('s4aStatus'),box=document.getElementById('s4aResults');if(!ta||!btn||!st||!box)return;if(!trackRadarMeta){st.textContent='Prima inserisci il link Spotify del brano.';return}const names=ta.value.split(String.fromCharCode(10)).map(x=>x.trim()).filter(Boolean).slice(0,20);if(!names.length){st.textContent='Inserisci almeno un nome playlist.';return}btn.disabled=true;st.textContent='Identifico '+names.length+' placement…';box.innerHTML='';try{const r=await fetch('/api/track-radar/import-match',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({names:names,track:trackRadarMeta.track,artist:trackRadarMeta.artist})});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Import fallito');const rows=Array.isArray(d.matches)?d.matches:[];const good=rows.filter(x=>x.status==='MATCHED'||x.status==='LIKELY').length,excluded=rows.filter(x=>x.status==='EXCLUDED').length;st.textContent=good+' identificati · '+excluded+' esclusi';for(const x of rows){const row=document.createElement('div');row.className='association';const b=document.createElement('b');b.textContent=x.name||x.inputName||'Playlist';row.appendChild(b);const m=document.createElement('div');m.className='status';m.style.marginTop='4px';m.textContent=(x.status||'REVIEW')+' · '+String(x.score||0)+'/100'+(x.owner?' · '+x.owner:(x.reason?' · '+x.reason:''));row.appendChild(m);if(x.spotifyUrl){const w=document.createElement('div');w.className='cardActions';const a=document.createElement('a');a.className='linkbtn';a.target='_blank';a.rel='noopener';a.href=x.spotifyUrl;a.textContent='Apri Spotify';w.appendChild(a);row.appendChild(w)}box.appendChild(row)}}catch(e){st.textContent=e.message||'Errore import'}finally{btn.disabled=false}}
document.addEventListener('click',function(e){if(e.target&&e.target.id==='s4aMatch')importS4APlacements()});
"""
s=s.replace(front,front+js,1)
backend='function trackRadarAlgorithmic(name)'
assert backend in s
helpers="""
function s4aNameScore(wanted,candidate){const a=normalize(wanted).replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim(),b=normalize(candidate).replace(/[^a-z0-9 ]/g,' ').replace(/\\s+/g,' ').trim();if(!a||!b)return 0;if(a===b)return 100;if(a.includes(b)||b.includes(a))return 92;const aw=new Set(a.split(' ').filter(x=>x.length>1)),bw=new Set(b.split(' ').filter(x=>x.length>1));const hit=[...aw].filter(x=>bw.has(x)).length;return Math.round(hit/Math.max(aw.size,bw.size)*88)}
async function s4aFindPlaylist(name,env){const qs=['site:open.spotify.com/playlist "'+name+'"','"'+name+'" Spotify playlist'];const batches=await Promise.all(qs.map(q=>smartSearch(q,env,12)));const urls=[];for(const b of batches){for(const r of b.results||[]){let u=cleanPlaylistUrl(r.url||'');if(!u){const m=String((r.title||'')+' '+(r.description||'')).match(/https?:\\/\\/open\\.spotify\\.com\\/playlist\\/[A-Za-z0-9]+/i);if(m)u=cleanPlaylistUrl(m[0])}if(u&&!urls.includes(u))urls.push(u)}}const found=[];for(const u of urls.slice(0,8)){try{const ident=await spotifyPlaylistIdentity(u,env);if(!ident)continue;const nm=String(ident.name||'').trim();found.push({name:nm||name,owner:String(ident.owner||''),spotifyUrl:u,score:s4aNameScore(name,nm||name)})}catch(e){}}found.sort((a,b)=>b.score-a.score);return found[0]||null}
async function s4aImport(input,env){const raw=Array.isArray(input?.names)?input.names:[],seen=new Set(),names=[];for(const v of raw){const n=String(v||'').trim(),k=normalize(n);if(n&&!seen.has(k)){seen.add(k);names.push(n)}}const out=[];for(const name of names.slice(0,20)){if(trackRadarAlgorithmic(name)){out.push({inputName:name,name:name,status:'EXCLUDED',score:100,reason:'Sorgente Spotify algoritmica / non curatoriale'});continue}const x=await s4aFindPlaylist(name,env);if(!x||x.score<55){out.push({inputName:name,name:name,status:'REVIEW',score:x?x.score:0,reason:'Nessun match pubblico sufficientemente affidabile'});continue}out.push({...x,inputName:name,status:x.score>=92?'MATCHED':'LIKELY'})}return {matches:out}}
"""
s=s.replace(backend,helpers+backend,1)
route="if(url.pathname==='/api/track-radar'&&request.method==='POST')"
assert route in s
s=s.replace(route,"if(url.pathname==='/api/track-radar/import-match'&&request.method==='POST'){try{return json(await s4aImport(await request.json(),env))}catch(e){return json({error:e.message||'Errore import placement'},500)}}"+route,1)
s=s.replace("const VERSION = 'RADAR v0.4.7.46 Cloud';","const VERSION = 'RADAR v0.4.7.47 Cloud';",1)
s=s.replace('<div class="version">v0.4.7.46</div>','<div class="version">v0.4.7.47</div>',1)
p.write_text(s)
